# Generated by Django 5.1.1 on 2024-10-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'اشتراک', 'verbose_name_plural': 'اشتراک ها'},
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='paypal_subscription_id',
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_subscription_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='شناسه پرداخت'),
        ),
    ]
