# Generated by Django 5.1.1 on 2024-10-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_cost',
            field=models.IntegerField(verbose_name='قیمت اشتراک'),
        ),
    ]
